import type { Metadata } from 'next'
import ToggleTheme from '../components/ToggleTheme'
import { ThemeProvider } from '../providers/Theme-Provider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ToggleTheme />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
